[package]
name = "bifrost"
version = "0.1.0"
authors = ["Lars Frogner <lars.frogner@astro.uio.no>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.2.0"
ndarray = "0.12.1"
byteorder = "1.3.2"
regex = "1.2.1"
serde = { version = "1.0", features = ["derive"] }
serde-pickle = "0.5.0"

[dev-dependencies]
ndarray-npy = { version = "0.4", default-features = false }
ndarray-stats = "0.2.0"