[package]
name = "bifrost"
version = "0.1.0"
authors = ["Lars Frogner <lars.frogner@astro.uio.no>"]
description = "Useful tools for working with Bifrost"
edition = "2018"
default-run = "bifrost"

[features]
default = ["cli"]
cli = ["clap"]
tracing = []
ebeam = ["nrfind"]

[dependencies]
# Dependencies for core
byteorder = "1.3.2"
ieee754 = "0.2.6"
itertools = "0.8.0"
lazy_static = "1.4.0"
ndarray = { version = "0.13.0", features = ["serde-1", "rayon"] }
num = "0.2.0"
rayon = "1.2.0"
rand = "0.7.2"
regex = "1.3.1"
serde = { version = "1.0.101", features = ["derive"] }
serde_json = "1.0.40"
serde-pickle = "0.5.1"

# Dependencies for cli
clap = { version = "2.33.0", optional = true }

# Dependencies for ebeam
nrfind = { version = "1.0.3", optional = true }

[dev-dependencies]
ndarray-stats = "0.3.0"

[profile.release]
debug = true
