[package]
name = "bifrost"
version = "0.1.0"
authors = ["Lars Frogner <lars.frogner@astro.uio.no>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.0"
num = "0.2.0"
ieee754 = "0.2.6"
ndarray = { version = "0.12.1", features = ["serde-1"] }
byteorder = "1.3.2"
regex = "1.2.1"
serde = { version = "1.0", features = ["derive"] }
serde-pickle = "0.5.0"

[dev-dependencies]
ndarray-stats = "0.2.0"

[profile.release]
debug = true