[package]
name = "backstaff"
version = "0.2.1"
authors = ["Lars Frogner <lars.frogner@astro.uio.no>"]
description = "A flexible tookit for working with Bifrost simulations"
edition = "2021"
default-run = "backstaff"

[features]
default = ["cli"]
cli = ["chrono", "clap", "clap_complete", "pad", "paste", "petgraph", "float-pretty-print"]
tracing = []
ebeam = []
netcdf = ["netcdf-rs"]
hdf5 = ["hdf5-rs"]

[dependencies]
# Dependencies for core
byteorder = "*"
ieee754 = "*"
itertools = "*"
lazy_static = "*"
ndarray = { version = "*", features = ["serde-1", "rayon"] }
ndarray-stats = "*"
noisy_float = "*"
num = "*"
rayon = "*"
rand = "*"
regex = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
serde-pickle = "*"
special = "*"
tempfile = "*"

# Dependencies for cli
chrono = { version = "*", optional = true }
clap = { version = ">=3.0.0", features = ["default", "cargo"], optional = true }
clap_complete = { version = "*", optional = true }
float-pretty-print = { version = "*", optional = true }
pad = { version = "*", optional = true }
paste = { version = "*", optional = true }
petgraph = { version = "*", features = [], optional = true }

# Dependencies for netcdf
netcdf-rs = { package = "netcdf", version = "*", optional = true}

# Dependencies for hdf5
hdf5-rs = { package = "hdf5", version = "*", optional = true}
