[package]
name = "backstaff"
version = "0.2.0"
authors = ["Lars Frogner <lars.frogner@astro.uio.no>"]
description = "A flexible tookit for working with Bifrost simulations"
edition = "2018"
default-run = "backstaff"

[features]
default = ["cli"]
cli = ["chrono", "clap", "pad", "paste", "petgraph", "float-pretty-print"]
tracing = []
ebeam = []
netcdf = ["netcdf-rs"]
hdf5 = ["hdf5-rs"]

[dependencies]
# Dependencies for core
byteorder = "1.3.4"
ieee754 = "0.2.6"
itertools = "0.9.0"
lazy_static = "1.4.0"
ndarray = { version = "0.13.0", features = ["serde-1", "rayon"] }
ndarray-stats = "0.3.0"
noisy_float = "0.1.12"
num = "0.2.1"
rayon = "1.3.0"
rand = "0.7.3"
regex = "1.3.5"
serde = { version = "1.0.105", features = ["derive"] }
serde_json = "1.0.44"
serde-pickle = "0.6.0"
special = "0.8.1"
tempfile = "3.1.0"

# Dependencies for cli
chrono = { version = "0.4.11", optional = true }
clap = { version = "2.33.0", features = ["suggestions", "color", "vec_map"], optional = true }
float-pretty-print = { version = "0.1.0", optional = true }
pad = { version = "0.1.6", optional = true }
paste = { version = "0.1.7", optional = true }
petgraph = { version = "0.5.0", features = [], optional = true }

# Dependencies for netcdf
netcdf-rs = { package = "netcdf", version = "0.4.1", optional = true}

# Dependencies for hdf5
hdf5-rs = { package = "hdf5", version = "0.6.0", optional = true}
